@startuml
'https://plantuml.com/sequence-diagram

autonumber

Cliente -> Servicio: pedirPedido(pedido,this)
Servicio-> Servicio: realizarPedido(pedido,cliente)
Servicio-> PedidoValidator: validarPedido(pedido,cliente)
Servicio-> RobotsService: getBuscadorRobots()
RobotsService -> BuscadorRobots: buscarRobots(List<> robots, pedido)
BuscadorRobots -> Empresa: getInstance().getRobots()
BuscadorRobots -> Servicio: return List<> robotsPedido
Servicio -> RobotsService: agregarPedidoRobots(pedido,List<> robotsPedido)



@enduml