@startuml
'https://plantuml.com/sequence-diagram

autonumber

Cliente -> Servicio: pedirPedido(pedido,this)
Servicio-> Servicio: realizarPedido(pedido,cliente)
Servicio-> PedidoValidator: validarPedido(pedido,cliente)
Servicio-> Pedido : requiereLimpieza()
Servicio-> BuscadorRobots: buscarRobots(pedidoLimpieza)
Servicio-> RobotsService: agregarPedidoRobots(robots)
Servicio-> Pedido: requiereReparacion()
Servicio-> BuscadorEmpleados: buscarEmpleado(pedidoReparacion)
Servicio-> Cliente: recibirMensaje(mensaje)
Servicio-> Cliente: agregarCostoPedido(precioDelPedido)
Servicio-> ActualizadorServicio: actualizarServicio(pedido,this)



@enduml