@startuml
'https://plantuml.com/sequence-diagram

autonumber

Cliente -> Servicio: pedirPedido(pedido)
Servicio -> Servicio : validarPedido(pedido)
Servicio -> Empresa: buscarRobots(pedido)
Servicio -> Empresa: agregarPedidoRobots(pedido)
Servicio -> Servicio: actualizarServicio(pedido)


@enduml